services:
  backend:
    build:
      context: go
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: dbData
        target: /data
        volume:
          nocopy: true
    environment:
      DATADIR: "/data"
      LISTEN_ADDR: ":8080"
      ADMIN_PASSWORD: "password"
      CORS_ARROWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
    depends_on:
      - "volume-owner"
  volume-owner:
    image: busybox:1.35
    command: |
      chown -R 65532:65532 /data
    volumes:
      - type: volume
        source: dbData
        target: /data
  client:
    build:
      context: client
    ports:
      - "3000:3000"
volumes:
  dbData:
