apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: chofu-race-course-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chofu-race-course-webapp
  template:
    metadata:
      labels:
        app: chofu-race-course-webapp
    spec:
      containers:
        - name: webapp
          image: ghcr.io/ueckoken/chofu-race-course-webapp:08e28a5-1665035404 # {"$imagepolicy": "flux-system:webapp"}
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
spec:
  selector:
    app: chofu-race-course-webapp
  ports:
    - protocol: TCP
      port: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: webapp
spec:
  ingressClassName: nginx
  rules:
    - host: kra.azukibar.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 3000
