// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file spec/v1/userdata.proto (package spec.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {UserDataRequest, UserDataResponse} from "./userdata_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service spec.v1.UserDataService
 */
export const UserDataService = {
  typeName: "spec.v1.UserDataService",
  methods: {
    /**
     * @generated from rpc spec.v1.UserDataService.UserData
     */
    userData: {
      name: "UserData",
      I: UserDataRequest,
      O: UserDataResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

