// @generated by protoc-gen-connect-web v0.2.1 with parameter "target=ts"
// @generated from file spec/v1/userdata.proto (package spec.v1, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {AllHorseDataRequest, AllHorseDataResponse, CreateUserRequest, CreateUserResponse, HorseDataRequest, HorseDataResponse, RaceDataRequest, RaceDataResponse, RangeRaceDataRequest, RangeRaceDataResponse, RegisterHorseRequest, RegisterHorseResponse, RegisterRaceRequest, RegisterRaceResponse, UserDataRequest, UserDataResponse, VoteRequest, VoteResponse} from "./userdata_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * ユーザのデータをやり取りするサービス
 *
 * @generated from service spec.v1.UserDataService
 */
export const UserDataService = {
  typeName: "spec.v1.UserDataService",
  methods: {
    /**
     * UserIdからUser情報を取得する
     *
     * @generated from rpc spec.v1.UserDataService.UserData
     */
    userData: {
      name: "UserData",
      I: UserDataRequest,
      O: UserDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * 新規Userを作成する
     *
     * @generated from rpc spec.v1.UserDataService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service spec.v1.HorseDataService
 */
export const HorseDataService = {
  typeName: "spec.v1.HorseDataService",
  methods: {
    /**
     * @generated from rpc spec.v1.HorseDataService.HorseData
     */
    horseData: {
      name: "HorseData",
      I: HorseDataRequest,
      O: HorseDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.v1.HorseDataService.AllHorseData
     */
    allHorseData: {
      name: "AllHorseData",
      I: AllHorseDataRequest,
      O: AllHorseDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.v1.HorseDataService.RegisterHorse
     */
    registerHorse: {
      name: "RegisterHorse",
      I: RegisterHorseRequest,
      O: RegisterHorseResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service spec.v1.RaceDataService
 */
export const RaceDataService = {
  typeName: "spec.v1.RaceDataService",
  methods: {
    /**
     * @generated from rpc spec.v1.RaceDataService.RangeRaceData
     */
    rangeRaceData: {
      name: "RangeRaceData",
      I: RangeRaceDataRequest,
      O: RangeRaceDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.v1.RaceDataService.RaceData
     */
    raceData: {
      name: "RaceData",
      I: RaceDataRequest,
      O: RaceDataResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc spec.v1.RaceDataService.RegisterRace
     */
    registerRace: {
      name: "RegisterRace",
      I: RegisterRaceRequest,
      O: RegisterRaceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service spec.v1.VoteService
 */
export const VoteService = {
  typeName: "spec.v1.VoteService",
  methods: {
    /**
     * @generated from rpc spec.v1.VoteService.Vote
     */
    vote: {
      name: "Vote",
      I: VoteRequest,
      O: VoteResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

