// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: spec/v1/userdata.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ユーザを表現する型
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ユーザID。他のIDはuint64であるが、ユーザIDのみJWTを使う都合上string。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ユーザID。他のIDはuint64であるが、ユーザIDのみJWTを使う都合上string。
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UserDataRequest) Reset() {
	*x = UserDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataRequest) ProtoMessage() {}

func (x *UserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataRequest.ProtoReflect.Descriptor instead.
func (*UserDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{1}
}

func (x *UserDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserDataResponse) Reset() {
	*x = UserDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResponse) ProtoMessage() {}

func (x *UserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResponse.ProtoReflect.Descriptor instead.
func (*UserDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{2}
}

func (x *UserDataResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type Horse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Horse) Reset() {
	*x = Horse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Horse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Horse) ProtoMessage() {}

func (x *Horse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Horse.ProtoReflect.Descriptor instead.
func (*Horse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{3}
}

func (x *Horse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Horse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 出走履歴のそれぞれ
type History struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 出走したレース
	Race *Race `protobuf:"bytes,1,opt,name=race,proto3" json:"race,omitempty"`
	// TODO: 分からん。誰か書いて。
	Order uint64 `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	// 順位。最も早くゴールしたときに1。
	Result uint64 `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *History) Reset() {
	*x = History{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*History) ProtoMessage() {}

func (x *History) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use History.ProtoReflect.Descriptor instead.
func (*History) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{4}
}

func (x *History) GetRace() *Race {
	if x != nil {
		return x.Race
	}
	return nil
}

func (x *History) GetOrder() uint64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *History) GetResult() uint64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type HorseDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner     string     `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Wins      uint64     `protobuf:"varint,3,opt,name=wins,proto3" json:"wins,omitempty"`
	Matches   uint64     `protobuf:"varint,4,opt,name=matches,proto3" json:"matches,omitempty"`
	Next      *uint64    `protobuf:"varint,5,opt,name=next,proto3,oneof" json:"next,omitempty"`
	Histories []*History `protobuf:"bytes,6,rep,name=histories,proto3" json:"histories,omitempty"`
}

func (x *HorseDetail) Reset() {
	*x = HorseDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseDetail) ProtoMessage() {}

func (x *HorseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseDetail.ProtoReflect.Descriptor instead.
func (*HorseDetail) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{5}
}

func (x *HorseDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HorseDetail) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *HorseDetail) GetWins() uint64 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *HorseDetail) GetMatches() uint64 {
	if x != nil {
		return x.Matches
	}
	return 0
}

func (x *HorseDetail) GetNext() uint64 {
	if x != nil && x.Next != nil {
		return *x.Next
	}
	return 0
}

func (x *HorseDetail) GetHistories() []*History {
	if x != nil {
		return x.Histories
	}
	return nil
}

type HorseDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HorseDataRequest) Reset() {
	*x = HorseDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseDataRequest) ProtoMessage() {}

func (x *HorseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseDataRequest.ProtoReflect.Descriptor instead.
func (*HorseDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{6}
}

func (x *HorseDataRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HorseDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Horse *HorseDetail `protobuf:"bytes,1,opt,name=horse,proto3" json:"horse,omitempty"`
}

func (x *HorseDataResponse) Reset() {
	*x = HorseDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorseDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseDataResponse) ProtoMessage() {}

func (x *HorseDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseDataResponse.ProtoReflect.Descriptor instead.
func (*HorseDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{7}
}

func (x *HorseDataResponse) GetHorse() *HorseDetail {
	if x != nil {
		return x.Horse
	}
	return nil
}

type AllHorseDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllHorseDataRequest) Reset() {
	*x = AllHorseDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllHorseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllHorseDataRequest) ProtoMessage() {}

func (x *AllHorseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllHorseDataRequest.ProtoReflect.Descriptor instead.
func (*AllHorseDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{8}
}

type AllHorseDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Horses []*Horse `protobuf:"bytes,1,rep,name=horses,proto3" json:"horses,omitempty"`
}

func (x *AllHorseDataResponse) Reset() {
	*x = AllHorseDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllHorseDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllHorseDataResponse) ProtoMessage() {}

func (x *AllHorseDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllHorseDataResponse.ProtoReflect.Descriptor instead.
func (*AllHorseDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{9}
}

func (x *AllHorseDataResponse) GetHorses() []*Horse {
	if x != nil {
		return x.Horses
	}
	return nil
}

type Race struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Order uint64                 `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Start *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
}

func (x *Race) Reset() {
	*x = Race{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Race) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Race) ProtoMessage() {}

func (x *Race) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Race.ProtoReflect.Descriptor instead.
func (*Race) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{10}
}

func (x *Race) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Race) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Race) GetOrder() uint64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Race) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order      uint64  `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
	Result     uint64  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	Horse      *Horse  `protobuf:"bytes,3,opt,name=horse,proto3" json:"horse,omitempty"`
	Odds       float64 `protobuf:"fixed64,4,opt,name=odds,proto3" json:"odds,omitempty"`
	Popularity uint64  `protobuf:"varint,5,opt,name=popularity,proto3" json:"popularity,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{11}
}

func (x *Member) GetOrder() uint64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Member) GetResult() uint64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Member) GetHorse() *Horse {
	if x != nil {
		return x.Horse
	}
	return nil
}

func (x *Member) GetOdds() float64 {
	if x != nil {
		return x.Odds
	}
	return 0
}

func (x *Member) GetPopularity() uint64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Horse  *Horse `protobuf:"bytes,1,opt,name=horse,proto3" json:"horse,omitempty"`
	Order  uint64 `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Return uint64 `protobuf:"varint,3,opt,name=return,proto3" json:"return,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{12}
}

func (x *Result) GetHorse() *Horse {
	if x != nil {
		return x.Horse
	}
	return nil
}

func (x *Result) GetOrder() uint64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Result) GetReturn() uint64 {
	if x != nil {
		return x.Return
	}
	return 0
}

type RaceDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Order       uint64                 `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	IsFinished  bool                   `protobuf:"varint,4,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	Member      []*Member              `protobuf:"bytes,5,rep,name=member,proto3" json:"member,omitempty"`
	Result      *Result                `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	Start       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start,proto3" json:"start,omitempty"`
	VoteBegin   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=vote_begin,json=voteBegin,proto3" json:"vote_begin,omitempty"`
	VoteEnd     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=vote_end,json=voteEnd,proto3" json:"vote_end,omitempty"`
}

func (x *RaceDetail) Reset() {
	*x = RaceDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceDetail) ProtoMessage() {}

func (x *RaceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceDetail.ProtoReflect.Descriptor instead.
func (*RaceDetail) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{13}
}

func (x *RaceDetail) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RaceDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RaceDetail) GetOrder() uint64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *RaceDetail) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *RaceDetail) GetMember() []*Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *RaceDetail) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RaceDetail) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RaceDetail) GetVoteBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.VoteBegin
	}
	return nil
}

func (x *RaceDetail) GetVoteEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.VoteEnd
	}
	return nil
}

type RangeRaceDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 指定した時間を含む、指定した時間からのデータを取得する。指定しなかったときは0(=1970年1月1日)と見なす。
	Begin *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=begin,proto3,oneof" json:"begin,omitempty"`
	// 指定した時間を含む、指定した時間までのデータを取得する。指定しなかったときは取得できる最新まで取得する。
	End *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3,oneof" json:"end,omitempty"`
}

func (x *RangeRaceDataRequest) Reset() {
	*x = RangeRaceDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeRaceDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRaceDataRequest) ProtoMessage() {}

func (x *RangeRaceDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRaceDataRequest.ProtoReflect.Descriptor instead.
func (*RangeRaceDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{14}
}

func (x *RangeRaceDataRequest) GetBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.Begin
	}
	return nil
}

func (x *RangeRaceDataRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type RangeRaceDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Races []*Race `protobuf:"bytes,1,rep,name=races,proto3" json:"races,omitempty"`
}

func (x *RangeRaceDataResponse) Reset() {
	*x = RangeRaceDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeRaceDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRaceDataResponse) ProtoMessage() {}

func (x *RangeRaceDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRaceDataResponse.ProtoReflect.Descriptor instead.
func (*RangeRaceDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{15}
}

func (x *RangeRaceDataResponse) GetRaces() []*Race {
	if x != nil {
		return x.Races
	}
	return nil
}

type RaceDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RaceId uint64 `protobuf:"varint,1,opt,name=race_id,json=raceId,proto3" json:"race_id,omitempty"`
}

func (x *RaceDataRequest) Reset() {
	*x = RaceDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaceDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceDataRequest) ProtoMessage() {}

func (x *RaceDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceDataRequest.ProtoReflect.Descriptor instead.
func (*RaceDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{16}
}

func (x *RaceDataRequest) GetRaceId() uint64 {
	if x != nil {
		return x.RaceId
	}
	return 0
}

type RaceDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Race *RaceDetail `protobuf:"bytes,1,opt,name=race,proto3" json:"race,omitempty"`
}

func (x *RaceDataResponse) Reset() {
	*x = RaceDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaceDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceDataResponse) ProtoMessage() {}

func (x *RaceDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceDataResponse.ProtoReflect.Descriptor instead.
func (*RaceDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{17}
}

func (x *RaceDataResponse) GetRace() *RaceDetail {
	if x != nil {
		return x.Race
	}
	return nil
}

var File_spec_v1_userdata_proto protoreflect.FileDescriptor

var file_spec_v1_userdata_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x16, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x2b, 0x0a,
	0x05, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x07, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61,
	0x63, 0x65, 0x52, 0x04, 0x72, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xb7, 0x01, 0x0a, 0x0b, 0x48, 0x6f, 0x72, 0x73, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x77, 0x69, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x77, 0x69, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x17,
	0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x04,
	0x6e, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x09, 0x68, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x70, 0x65,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x65, 0x78, 0x74,
	0x22, 0x22, 0x0a, 0x10, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x11, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x68, 0x6f, 0x72,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05,
	0x68, 0x6f, 0x72, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x14,
	0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x6f, 0x72, 0x73, 0x65, 0x52, 0x06, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x04,
	0x52, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x30,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x22, 0x90, 0x01, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x05, 0x68, 0x6f, 0x72,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x52, 0x05, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6f, 0x64, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6f,
	0x64, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x22, 0x5c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a,
	0x05, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x52, 0x05, 0x68, 0x6f,
	0x72, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x22, 0xeb, 0x02, 0x0a, 0x0a, 0x52, 0x61, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69,
	0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x39, 0x0a,
	0x0a, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x76,
	0x6f, 0x74, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x76, 0x6f, 0x74, 0x65,
	0x5f, 0x65, 0x6e, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x76, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x22,
	0x92, 0x01, 0x0a, 0x14, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x31, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x01, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x88,
	0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x65, 0x6e, 0x64, 0x22, 0x3c, 0x0a, 0x15, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x63,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x05, 0x72, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x52, 0x05, 0x72, 0x61, 0x63,
	0x65, 0x73, 0x22, 0x2a, 0x0a, 0x0f, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x22, 0x3b,
	0x0a, 0x10, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x72, 0x61, 0x63, 0x65, 0x32, 0x54, 0x0a, 0x0f, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x2e, 0x73, 0x70, 0x65,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x32, 0xa7, 0x01, 0x0a, 0x10, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f,
	0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c,
	0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x70, 0x65,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xa6, 0x01, 0x0a, 0x0f,
	0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x50, 0x0a, 0x0d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x41, 0x0a, 0x08, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x2e,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x75, 0x65, 0x63, 0x6b, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x63, 0x68, 0x6f, 0x66,
	0x75, 0x2d, 0x72, 0x61, 0x63, 0x65, 0x2d, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x67, 0x6f,
	0x2f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spec_v1_userdata_proto_rawDescOnce sync.Once
	file_spec_v1_userdata_proto_rawDescData = file_spec_v1_userdata_proto_rawDesc
)

func file_spec_v1_userdata_proto_rawDescGZIP() []byte {
	file_spec_v1_userdata_proto_rawDescOnce.Do(func() {
		file_spec_v1_userdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_v1_userdata_proto_rawDescData)
	})
	return file_spec_v1_userdata_proto_rawDescData
}

var file_spec_v1_userdata_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_spec_v1_userdata_proto_goTypes = []interface{}{
	(*User)(nil),                  // 0: spec.v1.User
	(*UserDataRequest)(nil),       // 1: spec.v1.UserDataRequest
	(*UserDataResponse)(nil),      // 2: spec.v1.UserDataResponse
	(*Horse)(nil),                 // 3: spec.v1.Horse
	(*History)(nil),               // 4: spec.v1.History
	(*HorseDetail)(nil),           // 5: spec.v1.HorseDetail
	(*HorseDataRequest)(nil),      // 6: spec.v1.HorseDataRequest
	(*HorseDataResponse)(nil),     // 7: spec.v1.HorseDataResponse
	(*AllHorseDataRequest)(nil),   // 8: spec.v1.AllHorseDataRequest
	(*AllHorseDataResponse)(nil),  // 9: spec.v1.AllHorseDataResponse
	(*Race)(nil),                  // 10: spec.v1.Race
	(*Member)(nil),                // 11: spec.v1.Member
	(*Result)(nil),                // 12: spec.v1.Result
	(*RaceDetail)(nil),            // 13: spec.v1.RaceDetail
	(*RangeRaceDataRequest)(nil),  // 14: spec.v1.RangeRaceDataRequest
	(*RangeRaceDataResponse)(nil), // 15: spec.v1.RangeRaceDataResponse
	(*RaceDataRequest)(nil),       // 16: spec.v1.RaceDataRequest
	(*RaceDataResponse)(nil),      // 17: spec.v1.RaceDataResponse
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_spec_v1_userdata_proto_depIdxs = []int32{
	0,  // 0: spec.v1.UserDataResponse.user:type_name -> spec.v1.User
	10, // 1: spec.v1.History.race:type_name -> spec.v1.Race
	4,  // 2: spec.v1.HorseDetail.histories:type_name -> spec.v1.History
	5,  // 3: spec.v1.HorseDataResponse.horse:type_name -> spec.v1.HorseDetail
	3,  // 4: spec.v1.AllHorseDataResponse.horses:type_name -> spec.v1.Horse
	18, // 5: spec.v1.Race.start:type_name -> google.protobuf.Timestamp
	3,  // 6: spec.v1.Member.horse:type_name -> spec.v1.Horse
	3,  // 7: spec.v1.Result.horse:type_name -> spec.v1.Horse
	11, // 8: spec.v1.RaceDetail.member:type_name -> spec.v1.Member
	12, // 9: spec.v1.RaceDetail.result:type_name -> spec.v1.Result
	18, // 10: spec.v1.RaceDetail.start:type_name -> google.protobuf.Timestamp
	18, // 11: spec.v1.RaceDetail.vote_begin:type_name -> google.protobuf.Timestamp
	18, // 12: spec.v1.RaceDetail.vote_end:type_name -> google.protobuf.Timestamp
	18, // 13: spec.v1.RangeRaceDataRequest.begin:type_name -> google.protobuf.Timestamp
	18, // 14: spec.v1.RangeRaceDataRequest.end:type_name -> google.protobuf.Timestamp
	10, // 15: spec.v1.RangeRaceDataResponse.races:type_name -> spec.v1.Race
	13, // 16: spec.v1.RaceDataResponse.race:type_name -> spec.v1.RaceDetail
	1,  // 17: spec.v1.UserDataService.UserData:input_type -> spec.v1.UserDataRequest
	6,  // 18: spec.v1.HorseDataService.HorseData:input_type -> spec.v1.HorseDataRequest
	8,  // 19: spec.v1.HorseDataService.AllHorseData:input_type -> spec.v1.AllHorseDataRequest
	14, // 20: spec.v1.RaceDataService.RangeRaceData:input_type -> spec.v1.RangeRaceDataRequest
	16, // 21: spec.v1.RaceDataService.RaceData:input_type -> spec.v1.RaceDataRequest
	2,  // 22: spec.v1.UserDataService.UserData:output_type -> spec.v1.UserDataResponse
	7,  // 23: spec.v1.HorseDataService.HorseData:output_type -> spec.v1.HorseDataResponse
	9,  // 24: spec.v1.HorseDataService.AllHorseData:output_type -> spec.v1.AllHorseDataResponse
	15, // 25: spec.v1.RaceDataService.RangeRaceData:output_type -> spec.v1.RangeRaceDataResponse
	17, // 26: spec.v1.RaceDataService.RaceData:output_type -> spec.v1.RaceDataResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_spec_v1_userdata_proto_init() }
func file_spec_v1_userdata_proto_init() {
	if File_spec_v1_userdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spec_v1_userdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Horse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*History); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorseDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorseDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorseDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllHorseDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllHorseDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Race); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaceDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeRaceDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeRaceDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaceDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaceDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_spec_v1_userdata_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_spec_v1_userdata_proto_msgTypes[14].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_v1_userdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_spec_v1_userdata_proto_goTypes,
		DependencyIndexes: file_spec_v1_userdata_proto_depIdxs,
		MessageInfos:      file_spec_v1_userdata_proto_msgTypes,
	}.Build()
	File_spec_v1_userdata_proto = out.File
	file_spec_v1_userdata_proto_rawDesc = nil
	file_spec_v1_userdata_proto_goTypes = nil
	file_spec_v1_userdata_proto_depIdxs = nil
}
