// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: spec/v1/userdata.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HorseDetail_Image_ImageType int32

const (
	HorseDetail_Image_IMAGE_TYPE_UNSPECIFIED HorseDetail_Image_ImageType = 0
	HorseDetail_Image_IMAGE_TYPE_PNG         HorseDetail_Image_ImageType = 1
	HorseDetail_Image_IMAGE_TYPE_JPEG        HorseDetail_Image_ImageType = 2
	HorseDetail_Image_IMAGE_TYPE_GIF         HorseDetail_Image_ImageType = 3
)

// Enum value maps for HorseDetail_Image_ImageType.
var (
	HorseDetail_Image_ImageType_name = map[int32]string{
		0: "IMAGE_TYPE_UNSPECIFIED",
		1: "IMAGE_TYPE_PNG",
		2: "IMAGE_TYPE_JPEG",
		3: "IMAGE_TYPE_GIF",
	}
	HorseDetail_Image_ImageType_value = map[string]int32{
		"IMAGE_TYPE_UNSPECIFIED": 0,
		"IMAGE_TYPE_PNG":         1,
		"IMAGE_TYPE_JPEG":        2,
		"IMAGE_TYPE_GIF":         3,
	}
)

func (x HorseDetail_Image_ImageType) Enum() *HorseDetail_Image_ImageType {
	p := new(HorseDetail_Image_ImageType)
	*p = x
	return p
}

func (x HorseDetail_Image_ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HorseDetail_Image_ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_v1_userdata_proto_enumTypes[0].Descriptor()
}

func (HorseDetail_Image_ImageType) Type() protoreflect.EnumType {
	return &file_spec_v1_userdata_proto_enumTypes[0]
}

func (x HorseDetail_Image_ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HorseDetail_Image_ImageType.Descriptor instead.
func (HorseDetail_Image_ImageType) EnumDescriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{7, 0, 0}
}

type RaceOrder_NoteType int32

const (
	RaceOrder_NOTE_TYPE_UNSPECIFIED RaceOrder_NoteType = 0
	// 出走取消
	RaceOrder_NOTE_TYPE_CANCEL RaceOrder_NoteType = 1
	// 競争中止
	RaceOrder_NOTE_TYPE_GIVEUP RaceOrder_NoteType = 2
)

// Enum value maps for RaceOrder_NoteType.
var (
	RaceOrder_NoteType_name = map[int32]string{
		0: "NOTE_TYPE_UNSPECIFIED",
		1: "NOTE_TYPE_CANCEL",
		2: "NOTE_TYPE_GIVEUP",
	}
	RaceOrder_NoteType_value = map[string]int32{
		"NOTE_TYPE_UNSPECIFIED": 0,
		"NOTE_TYPE_CANCEL":      1,
		"NOTE_TYPE_GIVEUP":      2,
	}
)

func (x RaceOrder_NoteType) Enum() *RaceOrder_NoteType {
	p := new(RaceOrder_NoteType)
	*p = x
	return p
}

func (x RaceOrder_NoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaceOrder_NoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_spec_v1_userdata_proto_enumTypes[1].Descriptor()
}

func (RaceOrder_NoteType) Type() protoreflect.EnumType {
	return &file_spec_v1_userdata_proto_enumTypes[1]
}

func (x RaceOrder_NoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaceOrder_NoteType.Descriptor instead.
func (RaceOrder_NoteType) EnumDescriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{15, 0}
}

// ユーザを表現する型
type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ユーザID。他のIDはuint32であるが、ユーザIDのみJWTを使う都合上string。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jwt *JWT `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *UserDataRequest) Reset() {
	*x = UserDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataRequest) ProtoMessage() {}

func (x *UserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataRequest.ProtoReflect.Descriptor instead.
func (*UserDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{1}
}

func (x *UserDataRequest) GetJwt() *JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

// JWTトークン
type JWT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *JWT) Reset() {
	*x = JWT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWT) ProtoMessage() {}

func (x *JWT) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWT.ProtoReflect.Descriptor instead.
func (*JWT) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{2}
}

func (x *JWT) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserDataResponse) Reset() {
	*x = UserDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDataResponse) ProtoMessage() {}

func (x *UserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDataResponse.ProtoReflect.Descriptor instead.
func (*UserDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{3}
}

func (x *UserDataResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{4}
}

// Deprecated: Do not use.
func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Jwt  *JWT  `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserResponse) GetJwt() *JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type Horse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 馬の名前
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Horse) Reset() {
	*x = Horse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Horse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Horse) ProtoMessage() {}

func (x *Horse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Horse.ProtoReflect.Descriptor instead.
func (*Horse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{6}
}

func (x *Horse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Horse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HorseDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  *Horse             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Owner string             `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Image *HorseDetail_Image `protobuf:"bytes,3,opt,name=image,proto3,oneof" json:"image,omitempty"`
	// 勝利数
	Wins uint32 `protobuf:"varint,4,opt,name=wins,proto3" json:"wins,omitempty"`
	// 試合数
	Matches uint32 `protobuf:"varint,5,opt,name=matches,proto3" json:"matches,omitempty"`
	// 次走、未定ならnull
	Next      *Race                  `protobuf:"bytes,6,opt,name=next,proto3,oneof" json:"next,omitempty"`
	Histories []*HorseDetail_History `protobuf:"bytes,7,rep,name=histories,proto3" json:"histories,omitempty"`
}

func (x *HorseDetail) Reset() {
	*x = HorseDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorseDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseDetail) ProtoMessage() {}

func (x *HorseDetail) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseDetail.ProtoReflect.Descriptor instead.
func (*HorseDetail) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{7}
}

func (x *HorseDetail) GetData() *Horse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HorseDetail) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *HorseDetail) GetImage() *HorseDetail_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *HorseDetail) GetWins() uint32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *HorseDetail) GetMatches() uint32 {
	if x != nil {
		return x.Matches
	}
	return 0
}

func (x *HorseDetail) GetNext() *Race {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *HorseDetail) GetHistories() []*HorseDetail_History {
	if x != nil {
		return x.Histories
	}
	return nil
}

type HorseDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HorseDataRequest) Reset() {
	*x = HorseDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseDataRequest) ProtoMessage() {}

func (x *HorseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseDataRequest.ProtoReflect.Descriptor instead.
func (*HorseDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{8}
}

func (x *HorseDataRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HorseDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Horse *HorseDetail `protobuf:"bytes,1,opt,name=horse,proto3" json:"horse,omitempty"`
}

func (x *HorseDataResponse) Reset() {
	*x = HorseDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorseDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseDataResponse) ProtoMessage() {}

func (x *HorseDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseDataResponse.ProtoReflect.Descriptor instead.
func (*HorseDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{9}
}

func (x *HorseDataResponse) GetHorse() *HorseDetail {
	if x != nil {
		return x.Horse
	}
	return nil
}

type AllHorseDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllHorseDataRequest) Reset() {
	*x = AllHorseDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllHorseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllHorseDataRequest) ProtoMessage() {}

func (x *AllHorseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllHorseDataRequest.ProtoReflect.Descriptor instead.
func (*AllHorseDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{10}
}

type AllHorseDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 登録している馬が1頭もいない場合は[]を返す。
	Horses []*Horse `protobuf:"bytes,1,rep,name=horses,proto3" json:"horses,omitempty"`
}

func (x *AllHorseDataResponse) Reset() {
	*x = AllHorseDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllHorseDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllHorseDataResponse) ProtoMessage() {}

func (x *AllHorseDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllHorseDataResponse.ProtoReflect.Descriptor instead.
func (*AllHorseDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{11}
}

func (x *AllHorseDataResponse) GetHorses() []*Horse {
	if x != nil {
		return x.Horses
	}
	return nil
}

// HorseDetailの初期値 id: id++, image: null, wins: 0, matches: 0, next: null, histories: []
type RegisterHorseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 所有者名
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *RegisterHorseRequest) Reset() {
	*x = RegisterHorseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterHorseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHorseRequest) ProtoMessage() {}

func (x *RegisterHorseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHorseRequest.ProtoReflect.Descriptor instead.
func (*RegisterHorseRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterHorseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterHorseRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type RegisterHorseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterHorseResponse) Reset() {
	*x = RegisterHorseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterHorseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHorseResponse) ProtoMessage() {}

func (x *RegisterHorseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHorseResponse.ProtoReflect.Descriptor instead.
func (*RegisterHorseResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{13}
}

type Race struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Order      uint32                 `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Start      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	IsFinished bool                   `protobuf:"varint,5,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
}

func (x *Race) Reset() {
	*x = Race{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Race) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Race) ProtoMessage() {}

func (x *Race) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Race.ProtoReflect.Descriptor instead.
func (*Race) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{14}
}

func (x *Race) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Race) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Race) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Race) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Race) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

type RaceOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to OrderOneof:
	//
	//	*RaceOrder_Order
	//	*RaceOrder_Note
	OrderOneof isRaceOrder_OrderOneof `protobuf_oneof:"order_oneof"`
}

func (x *RaceOrder) Reset() {
	*x = RaceOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaceOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceOrder) ProtoMessage() {}

func (x *RaceOrder) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceOrder.ProtoReflect.Descriptor instead.
func (*RaceOrder) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{15}
}

func (m *RaceOrder) GetOrderOneof() isRaceOrder_OrderOneof {
	if m != nil {
		return m.OrderOneof
	}
	return nil
}

func (x *RaceOrder) GetOrder() uint32 {
	if x, ok := x.GetOrderOneof().(*RaceOrder_Order); ok {
		return x.Order
	}
	return 0
}

func (x *RaceOrder) GetNote() RaceOrder_NoteType {
	if x, ok := x.GetOrderOneof().(*RaceOrder_Note); ok {
		return x.Note
	}
	return RaceOrder_NOTE_TYPE_UNSPECIFIED
}

type isRaceOrder_OrderOneof interface {
	isRaceOrder_OrderOneof()
}

type RaceOrder_Order struct {
	// 順位。最も早くゴールしたときに1。
	Order uint32 `protobuf:"varint,1,opt,name=order,proto3,oneof"`
}

type RaceOrder_Note struct {
	Note RaceOrder_NoteType `protobuf:"varint,2,opt,name=note,proto3,enum=spec.v1.RaceOrder_NoteType,oneof"`
}

func (*RaceOrder_Order) isRaceOrder_OrderOneof() {}

func (*RaceOrder_Note) isRaceOrder_OrderOneof() {}

type RaceDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        *Race                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Members     []*RaceDetail_Member   `protobuf:"bytes,4,rep,name=members,proto3" json:"members,omitempty"`
	VoteBegin   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=vote_begin,json=voteBegin,proto3" json:"vote_begin,omitempty"`
	VoteEnd     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=vote_end,json=voteEnd,proto3" json:"vote_end,omitempty"`
}

func (x *RaceDetail) Reset() {
	*x = RaceDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceDetail) ProtoMessage() {}

func (x *RaceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceDetail.ProtoReflect.Descriptor instead.
func (*RaceDetail) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{16}
}

func (x *RaceDetail) GetData() *Race {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RaceDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RaceDetail) GetMembers() []*RaceDetail_Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RaceDetail) GetVoteBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.VoteBegin
	}
	return nil
}

func (x *RaceDetail) GetVoteEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.VoteEnd
	}
	return nil
}

type RaceDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RaceDataRequest) Reset() {
	*x = RaceDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaceDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceDataRequest) ProtoMessage() {}

func (x *RaceDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceDataRequest.ProtoReflect.Descriptor instead.
func (*RaceDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{17}
}

func (x *RaceDataRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RaceDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Race *RaceDetail `protobuf:"bytes,1,opt,name=race,proto3" json:"race,omitempty"`
}

func (x *RaceDataResponse) Reset() {
	*x = RaceDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaceDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceDataResponse) ProtoMessage() {}

func (x *RaceDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceDataResponse.ProtoReflect.Descriptor instead.
func (*RaceDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{18}
}

func (x *RaceDataResponse) GetRace() *RaceDetail {
	if x != nil {
		return x.Race
	}
	return nil
}

type RangeRaceDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 指定した時間を含む、指定した時間からのデータを取得する。指定しなかったときは0(=1970年1月1日)と見なす。
	Begin *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=begin,proto3,oneof" json:"begin,omitempty"`
	// 指定した時間を含む、指定した時間までのデータを取得する。指定しなかったときは取得できる最新まで取得する。
	End *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3,oneof" json:"end,omitempty"`
}

func (x *RangeRaceDataRequest) Reset() {
	*x = RangeRaceDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeRaceDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRaceDataRequest) ProtoMessage() {}

func (x *RangeRaceDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRaceDataRequest.ProtoReflect.Descriptor instead.
func (*RangeRaceDataRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{19}
}

func (x *RangeRaceDataRequest) GetBegin() *timestamppb.Timestamp {
	if x != nil {
		return x.Begin
	}
	return nil
}

func (x *RangeRaceDataRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type RangeRaceDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Races []*Race `protobuf:"bytes,1,rep,name=races,proto3" json:"races,omitempty"`
}

func (x *RangeRaceDataResponse) Reset() {
	*x = RangeRaceDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeRaceDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRaceDataResponse) ProtoMessage() {}

func (x *RangeRaceDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRaceDataResponse.ProtoReflect.Descriptor instead.
func (*RangeRaceDataResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{20}
}

func (x *RangeRaceDataResponse) GetRaces() []*Race {
	if x != nil {
		return x.Races
	}
	return nil
}

// RaceDetailの初期値 id: id++, is_finished: false, members: [], vote_begin: start - n, vote_end: start - m
type RegisterRaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// その日の何番目のレースか
	Order uint32 `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	// 出走時刻
	Start *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	// コースなどの詳細説明
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *RegisterRaceRequest) Reset() {
	*x = RegisterRaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRaceRequest) ProtoMessage() {}

func (x *RegisterRaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRaceRequest.ProtoReflect.Descriptor instead.
func (*RegisterRaceRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterRaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRaceRequest) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *RegisterRaceRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RegisterRaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type RegisterRaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterRaceResponse) Reset() {
	*x = RegisterRaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRaceResponse) ProtoMessage() {}

func (x *RegisterRaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRaceResponse.ProtoReflect.Descriptor instead.
func (*RegisterRaceResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{22}
}

type VoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 投票するレースのID
	Race uint32 `protobuf:"varint,1,opt,name=race,proto3" json:"race,omitempty"`
	// 投票する馬の馬番
	Horse uint32 `protobuf:"varint,2,opt,name=horse,proto3" json:"horse,omitempty"`
	Jwt   *JWT   `protobuf:"bytes,3,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{23}
}

func (x *VoteRequest) GetRace() uint32 {
	if x != nil {
		return x.Race
	}
	return 0
}

func (x *VoteRequest) GetHorse() uint32 {
	if x != nil {
		return x.Horse
	}
	return 0
}

func (x *VoteRequest) GetJwt() *JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type VoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{24}
}

type HorseDetail_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 拡張子
	Type HorseDetail_Image_ImageType `protobuf:"varint,1,opt,name=type,proto3,enum=spec.v1.HorseDetail_Image_ImageType" json:"type,omitempty"`
	// base64形式
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HorseDetail_Image) Reset() {
	*x = HorseDetail_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorseDetail_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseDetail_Image) ProtoMessage() {}

func (x *HorseDetail_Image) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseDetail_Image.ProtoReflect.Descriptor instead.
func (*HorseDetail_Image) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{7, 0}
}

func (x *HorseDetail_Image) GetType() HorseDetail_Image_ImageType {
	if x != nil {
		return x.Type
	}
	return HorseDetail_Image_IMAGE_TYPE_UNSPECIFIED
}

func (x *HorseDetail_Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 出走履歴のそれぞれ
type HorseDetail_History struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 出走したレース
	Race *Race `protobuf:"bytes,1,opt,name=race,proto3" json:"race,omitempty"`
	// その日の何番目のレースか
	Order uint32 `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	// 順位
	Result *RaceOrder `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *HorseDetail_History) Reset() {
	*x = HorseDetail_History{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HorseDetail_History) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HorseDetail_History) ProtoMessage() {}

func (x *HorseDetail_History) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HorseDetail_History.ProtoReflect.Descriptor instead.
func (*HorseDetail_History) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{7, 1}
}

func (x *HorseDetail_History) GetRace() *Race {
	if x != nil {
		return x.Race
	}
	return nil
}

func (x *HorseDetail_History) GetOrder() uint32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *HorseDetail_History) GetResult() *RaceOrder {
	if x != nil {
		return x.Result
	}
	return nil
}

type RaceDetail_Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order      *RaceOrder `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Horse      *Horse     `protobuf:"bytes,2,opt,name=horse,proto3" json:"horse,omitempty"`
	Odds       float64    `protobuf:"fixed64,3,opt,name=odds,proto3" json:"odds,omitempty"`
	Popularity uint32     `protobuf:"varint,4,opt,name=popularity,proto3" json:"popularity,omitempty"`
}

func (x *RaceDetail_Member) Reset() {
	*x = RaceDetail_Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spec_v1_userdata_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaceDetail_Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceDetail_Member) ProtoMessage() {}

func (x *RaceDetail_Member) ProtoReflect() protoreflect.Message {
	mi := &file_spec_v1_userdata_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceDetail_Member.ProtoReflect.Descriptor instead.
func (*RaceDetail_Member) Descriptor() ([]byte, []int) {
	return file_spec_v1_userdata_proto_rawDescGZIP(), []int{16, 0}
}

func (x *RaceDetail_Member) GetOrder() *RaceOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *RaceDetail_Member) GetHorse() *Horse {
	if x != nil {
		return x.Horse
	}
	return nil
}

func (x *RaceDetail_Member) GetOdds() float64 {
	if x != nil {
		return x.Odds
	}
	return 0
}

func (x *RaceDetail_Member) GetPopularity() uint32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

var File_spec_v1_userdata_proto protoreflect.FileDescriptor

var file_spec_v1_userdata_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x16, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x0f, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x03, 0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x70, 0x65,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x57, 0x54, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x22, 0x1b, 0x0a,
	0x03, 0x4a, 0x57, 0x54, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x35, 0x0a, 0x10, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x22, 0x3a, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x42, 0x02, 0x18, 0x01, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x57, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x57,
	0x54, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x22, 0x2b, 0x0a, 0x05, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xd1, 0x04, 0x0a, 0x0b, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73,
	0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x35, 0x0a,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x48,
	0x01, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x09, 0x68, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x1a, 0xbb, 0x01, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24,
	0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x64,
	0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x49,
	0x4d, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4d, 0x41, 0x47, 0x45,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49,
	0x4d, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4a, 0x50, 0x45, 0x47, 0x10, 0x02,
	0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47,
	0x49, 0x46, 0x10, 0x03, 0x1a, 0x6e, 0x0a, 0x07, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x21, 0x0a, 0x04, 0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x52, 0x04, 0x72, 0x61,
	0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x48, 0x6f, 0x72, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x11, 0x48,
	0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x05, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x22, 0x15, 0x0a, 0x13,
	0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x68,
	0x6f, 0x72, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x70,
	0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x52, 0x06, 0x68, 0x6f, 0x72,
	0x73, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48,
	0x6f, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x93,
	0x01, 0x0a, 0x04, 0x52, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x22, 0xb8, 0x01, 0x0a, 0x09, 0x52, 0x61, 0x63, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x22, 0x51, 0x0a,
	0x08, 0x4e, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4e, 0x4f, 0x54,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x4f, 0x54, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4e, 0x4f,
	0x54, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x49, 0x56, 0x45, 0x55, 0x50, 0x10, 0x02,
	0x42, 0x0d, 0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x22,
	0x88, 0x03, 0x0a, 0x0a, 0x52, 0x61, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x21,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x61, 0x63, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x76, 0x6f, 0x74,
	0x65, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x76, 0x6f, 0x74, 0x65, 0x42,
	0x65, 0x67, 0x69, 0x6e, 0x12, 0x35, 0x0a, 0x08, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x07, 0x76, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x1a, 0x8c, 0x01, 0x0a, 0x06,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x61, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x24, 0x0a, 0x05, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x52,
	0x05, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x64, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6f, 0x64, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f,
	0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x22, 0x21, 0x0a, 0x0f, 0x52, 0x61,
	0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a,
	0x10, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x04, 0x72, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x72, 0x61, 0x63, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x14, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00,
	0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x03, 0x65, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x48, 0x01, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x6e, 0x64, 0x22,
	0x3c, 0x0a, 0x15, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x72, 0x61, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x52, 0x05, 0x72, 0x61, 0x63, 0x65, 0x73, 0x22, 0x93, 0x01,
	0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x57, 0x0a, 0x0b, 0x56,
	0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x72, 0x61, 0x63, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x68, 0x6f, 0x72, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x68,
	0x6f, 0x72, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4a, 0x57, 0x54, 0x52,
	0x03, 0x6a, 0x77, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x9d, 0x01, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x32, 0xf9, 0x01, 0x0a, 0x10, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x48, 0x6f, 0x72,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x72, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4d, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1c, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72,
	0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x48, 0x6f, 0x72, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50,
	0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x12,
	0x1d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x48, 0x6f, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x32, 0xf5, 0x01, 0x0a, 0x0f, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x63,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x08, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73,
	0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0c, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x61, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x44, 0x0a, 0x0b, 0x56, 0x6f, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x56, 0x6f, 0x74, 0x65, 0x12,
	0x14, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x39,
	0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x65, 0x63,
	0x6b, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x63, 0x68, 0x6f, 0x66, 0x75, 0x2d, 0x72, 0x61, 0x63, 0x65,
	0x2d, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x67, 0x6f, 0x2f, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_spec_v1_userdata_proto_rawDescOnce sync.Once
	file_spec_v1_userdata_proto_rawDescData = file_spec_v1_userdata_proto_rawDesc
)

func file_spec_v1_userdata_proto_rawDescGZIP() []byte {
	file_spec_v1_userdata_proto_rawDescOnce.Do(func() {
		file_spec_v1_userdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_spec_v1_userdata_proto_rawDescData)
	})
	return file_spec_v1_userdata_proto_rawDescData
}

var file_spec_v1_userdata_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_spec_v1_userdata_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_spec_v1_userdata_proto_goTypes = []interface{}{
	(HorseDetail_Image_ImageType)(0), // 0: spec.v1.HorseDetail.Image.ImageType
	(RaceOrder_NoteType)(0),          // 1: spec.v1.RaceOrder.NoteType
	(*User)(nil),                     // 2: spec.v1.User
	(*UserDataRequest)(nil),          // 3: spec.v1.UserDataRequest
	(*JWT)(nil),                      // 4: spec.v1.JWT
	(*UserDataResponse)(nil),         // 5: spec.v1.UserDataResponse
	(*CreateUserRequest)(nil),        // 6: spec.v1.CreateUserRequest
	(*CreateUserResponse)(nil),       // 7: spec.v1.CreateUserResponse
	(*Horse)(nil),                    // 8: spec.v1.Horse
	(*HorseDetail)(nil),              // 9: spec.v1.HorseDetail
	(*HorseDataRequest)(nil),         // 10: spec.v1.HorseDataRequest
	(*HorseDataResponse)(nil),        // 11: spec.v1.HorseDataResponse
	(*AllHorseDataRequest)(nil),      // 12: spec.v1.AllHorseDataRequest
	(*AllHorseDataResponse)(nil),     // 13: spec.v1.AllHorseDataResponse
	(*RegisterHorseRequest)(nil),     // 14: spec.v1.RegisterHorseRequest
	(*RegisterHorseResponse)(nil),    // 15: spec.v1.RegisterHorseResponse
	(*Race)(nil),                     // 16: spec.v1.Race
	(*RaceOrder)(nil),                // 17: spec.v1.RaceOrder
	(*RaceDetail)(nil),               // 18: spec.v1.RaceDetail
	(*RaceDataRequest)(nil),          // 19: spec.v1.RaceDataRequest
	(*RaceDataResponse)(nil),         // 20: spec.v1.RaceDataResponse
	(*RangeRaceDataRequest)(nil),     // 21: spec.v1.RangeRaceDataRequest
	(*RangeRaceDataResponse)(nil),    // 22: spec.v1.RangeRaceDataResponse
	(*RegisterRaceRequest)(nil),      // 23: spec.v1.RegisterRaceRequest
	(*RegisterRaceResponse)(nil),     // 24: spec.v1.RegisterRaceResponse
	(*VoteRequest)(nil),              // 25: spec.v1.VoteRequest
	(*VoteResponse)(nil),             // 26: spec.v1.VoteResponse
	(*HorseDetail_Image)(nil),        // 27: spec.v1.HorseDetail.Image
	(*HorseDetail_History)(nil),      // 28: spec.v1.HorseDetail.History
	(*RaceDetail_Member)(nil),        // 29: spec.v1.RaceDetail.Member
	(*timestamppb.Timestamp)(nil),    // 30: google.protobuf.Timestamp
}
var file_spec_v1_userdata_proto_depIdxs = []int32{
	4,  // 0: spec.v1.UserDataRequest.jwt:type_name -> spec.v1.JWT
	2,  // 1: spec.v1.UserDataResponse.user:type_name -> spec.v1.User
	2,  // 2: spec.v1.CreateUserRequest.user:type_name -> spec.v1.User
	2,  // 3: spec.v1.CreateUserResponse.user:type_name -> spec.v1.User
	4,  // 4: spec.v1.CreateUserResponse.jwt:type_name -> spec.v1.JWT
	8,  // 5: spec.v1.HorseDetail.data:type_name -> spec.v1.Horse
	27, // 6: spec.v1.HorseDetail.image:type_name -> spec.v1.HorseDetail.Image
	16, // 7: spec.v1.HorseDetail.next:type_name -> spec.v1.Race
	28, // 8: spec.v1.HorseDetail.histories:type_name -> spec.v1.HorseDetail.History
	9,  // 9: spec.v1.HorseDataResponse.horse:type_name -> spec.v1.HorseDetail
	8,  // 10: spec.v1.AllHorseDataResponse.horses:type_name -> spec.v1.Horse
	30, // 11: spec.v1.Race.start:type_name -> google.protobuf.Timestamp
	1,  // 12: spec.v1.RaceOrder.note:type_name -> spec.v1.RaceOrder.NoteType
	16, // 13: spec.v1.RaceDetail.data:type_name -> spec.v1.Race
	29, // 14: spec.v1.RaceDetail.members:type_name -> spec.v1.RaceDetail.Member
	30, // 15: spec.v1.RaceDetail.vote_begin:type_name -> google.protobuf.Timestamp
	30, // 16: spec.v1.RaceDetail.vote_end:type_name -> google.protobuf.Timestamp
	18, // 17: spec.v1.RaceDataResponse.race:type_name -> spec.v1.RaceDetail
	30, // 18: spec.v1.RangeRaceDataRequest.begin:type_name -> google.protobuf.Timestamp
	30, // 19: spec.v1.RangeRaceDataRequest.end:type_name -> google.protobuf.Timestamp
	16, // 20: spec.v1.RangeRaceDataResponse.races:type_name -> spec.v1.Race
	30, // 21: spec.v1.RegisterRaceRequest.start:type_name -> google.protobuf.Timestamp
	4,  // 22: spec.v1.VoteRequest.jwt:type_name -> spec.v1.JWT
	0,  // 23: spec.v1.HorseDetail.Image.type:type_name -> spec.v1.HorseDetail.Image.ImageType
	16, // 24: spec.v1.HorseDetail.History.race:type_name -> spec.v1.Race
	17, // 25: spec.v1.HorseDetail.History.result:type_name -> spec.v1.RaceOrder
	17, // 26: spec.v1.RaceDetail.Member.order:type_name -> spec.v1.RaceOrder
	8,  // 27: spec.v1.RaceDetail.Member.horse:type_name -> spec.v1.Horse
	3,  // 28: spec.v1.UserDataService.UserData:input_type -> spec.v1.UserDataRequest
	6,  // 29: spec.v1.UserDataService.CreateUser:input_type -> spec.v1.CreateUserRequest
	10, // 30: spec.v1.HorseDataService.HorseData:input_type -> spec.v1.HorseDataRequest
	12, // 31: spec.v1.HorseDataService.AllHorseData:input_type -> spec.v1.AllHorseDataRequest
	14, // 32: spec.v1.HorseDataService.RegisterHorse:input_type -> spec.v1.RegisterHorseRequest
	21, // 33: spec.v1.RaceDataService.RangeRaceData:input_type -> spec.v1.RangeRaceDataRequest
	19, // 34: spec.v1.RaceDataService.RaceData:input_type -> spec.v1.RaceDataRequest
	23, // 35: spec.v1.RaceDataService.RegisterRace:input_type -> spec.v1.RegisterRaceRequest
	25, // 36: spec.v1.VoteService.Vote:input_type -> spec.v1.VoteRequest
	5,  // 37: spec.v1.UserDataService.UserData:output_type -> spec.v1.UserDataResponse
	7,  // 38: spec.v1.UserDataService.CreateUser:output_type -> spec.v1.CreateUserResponse
	11, // 39: spec.v1.HorseDataService.HorseData:output_type -> spec.v1.HorseDataResponse
	13, // 40: spec.v1.HorseDataService.AllHorseData:output_type -> spec.v1.AllHorseDataResponse
	15, // 41: spec.v1.HorseDataService.RegisterHorse:output_type -> spec.v1.RegisterHorseResponse
	22, // 42: spec.v1.RaceDataService.RangeRaceData:output_type -> spec.v1.RangeRaceDataResponse
	20, // 43: spec.v1.RaceDataService.RaceData:output_type -> spec.v1.RaceDataResponse
	24, // 44: spec.v1.RaceDataService.RegisterRace:output_type -> spec.v1.RegisterRaceResponse
	26, // 45: spec.v1.VoteService.Vote:output_type -> spec.v1.VoteResponse
	37, // [37:46] is the sub-list for method output_type
	28, // [28:37] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_spec_v1_userdata_proto_init() }
func file_spec_v1_userdata_proto_init() {
	if File_spec_v1_userdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spec_v1_userdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JWT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Horse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorseDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorseDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorseDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllHorseDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllHorseDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterHorseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterHorseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Race); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaceOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaceDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaceDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaceDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeRaceDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeRaceDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorseDetail_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HorseDetail_History); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spec_v1_userdata_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaceDetail_Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_spec_v1_userdata_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_spec_v1_userdata_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*RaceOrder_Order)(nil),
		(*RaceOrder_Note)(nil),
	}
	file_spec_v1_userdata_proto_msgTypes[19].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spec_v1_userdata_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_spec_v1_userdata_proto_goTypes,
		DependencyIndexes: file_spec_v1_userdata_proto_depIdxs,
		EnumInfos:         file_spec_v1_userdata_proto_enumTypes,
		MessageInfos:      file_spec_v1_userdata_proto_msgTypes,
	}.Build()
	File_spec_v1_userdata_proto = out.File
	file_spec_v1_userdata_proto_rawDesc = nil
	file_spec_v1_userdata_proto_goTypes = nil
	file_spec_v1_userdata_proto_depIdxs = nil
}
