apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: file-owner
          image: ghcr.io/ueckoken/chofu-race-course-api-owner:latest
          volumeMounts:
            - mountPath: /app
              name: database
      containers:
        - name: api
          image: ghcr.io/ueckoken/chofu-race-course-api:08e28a5-1665035394
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: database
          env:
            - name: DATADIR
              value: /data
            - name: LISTEN_ADDR
              value: ":8080"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminPassword
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: data-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8080
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-server-pvc
  namespace: api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
