import { FC } from "react";
import Head from "next/head";

const SpecialPage: FC<{}> = () => {
    return (
        <>
            <Head>
                <title>新馬王戦 | 調布競馬ポータル</title>
            </Head>
            <h2>新馬王戦</h2>
            <h3>日程</h3>
            <table>
                <tbody>
                    <tr>
                        <td>2022年10月7日</td>
                        <td>レース1日目</td>
                    </tr>
                    <tr>
                        <td>2022年10月14日</td>
                        <td>レース2日目</td>
                    </tr>
                    <tr>
                        <td>2022年10月21日</td>
                        <td>レース3日目</td>
                    </tr>
                    <tr>
                        <td>2022年10月28日</td>
                        <td>レース最終日/表彰/エキシビジョンレース</td>
                    </tr>
                </tbody>
            </table>
            <h3>ランキング</h3>
            <p>1日目終了時点</p>
            <table>
                <thead>
                    <tr>
                        <th>順位</th>
                        <th>馬名</th>
                        <th>得点</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>ラズリアンクロス</td>
                        <td>12</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>エイシャオラー</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>オゼハカイザイダン</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>オタクカエルヨー</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>サクラモッチリーン</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>ネイバオキリコミ</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>ハリボテエレジー</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>ライラックアロー</td>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>レモナーノナレハテ</td>
                        <td>2</td>
                    </tr>
                </tbody>
            </table>
            <p>合計点の平均を得点とする。着順ごとの獲得点は以下の通り。</p>
            <table>
                <thead>
                    <tr>
                        <th>頭数</th>
                        <th>1着</th>
                        <th>2着</th>
                        <th>3着</th>
                        <th>4着</th>
                        <th>中止</th>
                        <th>除外</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>4頭</td>
                        <td>12点</td>
                        <td>6点</td>
                        <td>4点</td>
                        <td>3点</td>
                        <td>2点</td>
                        <td>0点</td>
                    </tr>
                    <tr>
                        <td>3頭</td>
                        <td>12点</td>
                        <td>5点</td>
                        <td>3点</td>
                        <td></td>
                        <td>2点</td>
                        <td>0点</td>
                    </tr>
                    <tr>
                        <td>2頭</td>
                        <td>12点</td>
                        <td>3点</td>
                        <td></td>
                        <td></td>
                        <td>2点</td>
                        <td>0点</td>
                    </tr>
                </tbody>
            </table>
            <p>同着の場合は1つ下の順位の得点との平均を取る。</p>
        </>
    );
};

export default SpecialPage;
