apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: general
  secretRef:
    name: discord-url
# ---
# apiVersion: notification.toolkit.fluxcd.io/v1beta1
# kind: Alert
# metadata:
#   name: on-call-webapp
#   namespace: flux-system
# spec:
#   summary: "実運用サーバ"
#   providerRef:
#     name: discord
#   eventSeverity: info
#   eventSources:
#     - kind: Kustomization
#       name: "*"
