name: check_ts

on:
  push:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml
      - client/**
      - proto/**/*.proto

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: client/yarn.lock
      - run: yarn install
        working-directory: ./client
      - run: yarn run check
        working-directory: ./client
